LOCAL_FILES += \
	draw.c gles.cpp \
	GLSLProgObj.cpp \
	GlProgramObject.cpp \
	GlProgramDescDefault.cpp \
	GlProgramDescRgbaShow.cpp \
	GlProgramDescDrawRect.cpp \
	GLSLProgObjDrawRect.cpp GLSLProgObjRGBA.cpp \
	shader.c Shader.cpp \
	texture.c \

LOCAL_LIB = libgles.a
