# Makefile

all:
	@echo http://blog.csdn.net/bat603/article/details/1176251
	gcc pcap_1.c -g -o pcap_1 -lpcap
	gcc pcap_2.c -g -o pcap_2 -lpcap
	gcc pcap_3.c -g -o pcap_3 -lpcap
	gcc pcap_4.c -g -o pcap_4 -lpcap
